#! /bin/sh

sxhkd &
lxappearance &
pulseaudio --kill &
iwctl --passphrase 9CC8FC90AB34 station wlan0 connect IZZI-AB34 &
pulseaudio --start &
/usr/lib/x86_64-linux-gnu/libexec/polkit-kde-authentication-agent-1 &
#nm-applet &
#dunst&
#wxfce4-volumed &
#compton --config /home/lgsmarttv/.config/compton/compton.conf &
#~/.config/polybar/launch.sh &
#feh --bg-fill /usr/share/wallpapers/Path/contents/images/2560x1600.jpg &
#tint2 &
feh --bg-fill /home/miguel/.config/openbox/gatonegro.jpg &
#feh --bg-fill /usr/share/wallpapers/Path/contents/images/2560x1600.jpg &



bspc monitor -d 1 2 3 4

bspc config border_width         1
bspc config window_gap           0

#bspc config click_to_focus any
#any

bspc config focus_follows_pointer true
#swallow_first_click true


#bspc config normal_border_color "$color8"
#bspc config active_border_color "$color7"
#bspc config focused_border_color "#04B404"
bspc config focused_border_color "#ffbd33"
#bspc config presel_feedback_color "#ff5733"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc config pointer_action1 move
#bspc config pointer_action2 resize_side
#bspc config pointer_action3 resize_corner

#follow=on sigue a la aplcacion si estas en otro escritorio.

bspc rule -a Firefox desktop= '^4' follow=on
#bspc rule -a Thunar desktop='^1' state=floating follow=on
#bspc rule -a Thunar desktop='^1' follow=on focus=of manage=off

#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
